export const ADD_POSTS = "ADD_POSTS";
export const ADD_POST_LIKE = "ADD_POST_LIKE";
export const DELETE_POST_LIKE = "DELETE_POST_LIKE";
export const ADD_COMMENT_LIKE = "ADD_COMMENT_LIKE";
export const DELETE_COMMENT_LIKE = "DELETE_COMMENT_LIKE";
export const ADD_COMMENT = "ADD_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";